In [82]:
import pandas as pd
import numpy as np

df = pd.read_csv('train_data.csv')
df.head()

,case_id,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,patientid,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,Stay
0,1,8,c,3,Z,3,radiotherapy,R,F,2.0,31397,7.0,Emergency,Extreme,2,51-60,4911.0,0-10
1,2,2,c,5,Z,2,radiotherapy,S,F,2.0,31397,7.0,Trauma,Extreme,2,51-60,5954.0,41-50
2,3,10,e,1,X,2,anesthesia,S,E,2.0,31397,7.0,Trauma,Extreme,2,51-60,4745.0,31-40
3,4,26,b,2,Y,2,radiotherapy,R,D,2.0,31397,7.0,Trauma,Extreme,2,51-60,7272.0,41-50
4,5,26,b,2,Y,2,radiotherapy,S,D,2.0,31397,7.0,Trauma,Extreme,2,51-60,5558.0,41-50

In [83]:
df.info()
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318438 entries, 0 to 318437
Data columns (total 18 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   case_id                            318438 non-null  int64
 1   Hospital_code                      318438 non-null  int64
 2   Hospital_type_code                 318438 non-null  object
 3   City_Code_Hospital                 318438 non-null  int64
 4   Hospital_region_code               318438 non-null  object
 5   Available Extra Rooms in Hospital  318438 non-null  int64
 6   Department                         318438 non-null  object
 7   Ward_Type                          318438 non-null  object
 8   Ward_Facility_Code                 318438 non-null  object
 9   Bed Grade                          318325 non-null  float64
 10  patientid                          318438 non-null  int64
 11  City_Code_Patient                  313906 non-null  float64
 12  Type of Admission                  318438 non-null  object
 13  Severity of Illness                318438 non-null  object
 14  Visitors with Patient              318438 non-null  int64
 15  Age                                318438 non-null  object
 16  Admission_Deposit                  318438 non-null  float64
 17  Stay                               318438 non-null  object
dtypes: float64(3), int64(6), object(9)
memory usage: 43.7+ MB

,case_id,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,patientid,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,Stay
count,318438.000000,318438.000000,318438,318438.000000,318438,318438.000000,318438,318438,318438,318325.000000,318438.000000,313906.000000,318438,318438,318438.000000,318438,318438.000000,318438
unique,NaN,NaN,7,NaN,3,NaN,5,6,6,NaN,NaN,NaN,3,3,NaN,10,NaN,11
top,NaN,NaN,a,NaN,X,NaN,gynecology,R,F,NaN,NaN,NaN,Trauma,Moderate,NaN,41-50,NaN,21-30
freq,NaN,NaN,143425,NaN,133336,NaN,249486,127947,112753,NaN,NaN,NaN,152261,175843,NaN,63749,NaN,87491
mean,159219.500000,18.318841,NaN,4.771717,NaN,3.197627,NaN,NaN,NaN,2.625807,65747.579472,7.251859,NaN,NaN,3.284099,NaN,4880.749392,NaN
std,91925.276847,8.633755,NaN,3.102535,NaN,1.168171,NaN,NaN,NaN,0.873146,37979.936440,4.745266,NaN,NaN,1.764061,NaN,1086.776254,NaN
min,1.000000,1.000000,NaN,1.000000,NaN,0.000000,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,NaN,0.000000,NaN,1800.000000,NaN
25%,79610.250000,11.000000,NaN,2.000000,NaN,2.000000,NaN,NaN,NaN,2.000000,32847.000000,4.000000,NaN,NaN,2.000000,NaN,4186.000000,NaN
50%,159219.500000,19.000000,NaN,5.000000,NaN,3.000000,NaN,NaN,NaN,3.000000,65724.500000,8.000000,NaN,NaN,3.000000,NaN,4741.000000,NaN
75%,238828.750000,26.000000,NaN,7.000000,NaN,4.000000,NaN,NaN,NaN,3.000000,98470.000000,8.000000,NaN,NaN,4.000000,NaN,5409.000000,NaN
max,318438.000000,32.000000,NaN,13.000000,NaN,24.000000,NaN,NaN,NaN,4.000000,131624.000000,38.000000,NaN,NaN,32.000000,NaN,11008.000000,NaN

In [84]:
df.isnull().sum()
df.duplicated().sum()

0

In [85]:
df['target'] = df['Stay'].apply(lambda x: 1 if x in ['0-10','11-20','21-30'] else 0)

In [86]:
num_cols = df.select_dtypes(include=['int64','float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')
    df[col].fillna(df[col].median(), inplace=True)

for col in cat_cols:
    df[col] = df[col].astype(str).str.lower().str.strip()
    df[col].fillna(df[col].mode()[0], inplace=True)

df = df.drop_duplicates()

C:\Users\SHREE\AppData\Local\Temp\ipykernel_17904\1874458856.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SHREE\AppData\Local\Temp\ipykernel_17904\1874458856.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
C:\Users\SHREE\AppData\Local\Temp\ipykernel_17904\1874458856.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
C:\Users\SHREE\AppData\Local\Temp\ipykernel_17904\1874458856.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
C:\Users\SHREE\AppData\Local\Temp\ipykernel_17904\1874458856.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
C:\Users\SHREE\AppData\Local\Temp\ipykernel_17904\1874458856.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
C:\Users\SHREE\AppData\Local\Temp\ipykernel_17904\1874458856.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
C:\Users\SHREE\AppData\Local\Temp\ipykernel_17904\1874458856.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
C:\Users\SHREE\AppData\Local\Temp\ipykernel_17904\1874458856.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
C:\Users\SHREE\AppData\Local\Temp\ipykernel_17904\1874458856.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [90]:
df['age_group'] = df['Age'].apply(lambda x: 0 if float(x[-2:]) < 30 else 1 if float(x[-2:]) < 60 else 2)

df['severity_flag'] = df['Severity of Illness'].map({
    'minor': 0,
    'moderate': 1,
    'extreme': 2
})

df['resource_usage'] = df['Visitors with Patient'] * df['Admission_Deposit']

In [91]:
df = df.drop(['Stay'], axis=1)

In [92]:
df.to_csv('clean_data.csv', index=False)

- Target derived from Stay to reflect 30-day readmission risk
- Missing values handled using median/mode for robustness
- Age grouped to reduce noise and capture nonlinear trends
- Severity encoded ordinally to preserve ranking
- Interaction feature captures hospital resource usage

# **Medium**

In [93]:
import pandas as pd
import numpy as np

df = pd.read_csv('clean_data.csv')

In [94]:
TARGET = 'target'
ID_COLS = ['case_id','patientid']

X = df.drop(ID_COLS + [TARGET], axis=1, errors='ignore')
y = df[TARGET]

In [95]:
X = pd.get_dummies(X, drop_first=True)

In [96]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y
)

In [97]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=300, class_weight='balanced')
lr.fit(X_train, y_train)

c:\Users\SHREE\miniconda3\envs\mgenv\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 300 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=300).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(class_weight='balanced', max_iter=300)

In [98]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=150, class_weight='balanced')
rf.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=150)

In [99]:
from sklearn.metrics import f1_score, roc_auc_score

lr_preds = lr.predict(X_test)
rf_preds = rf.predict(X_test)

print("LR F1:", f1_score(y_test, lr_preds))
print("RF F1:", f1_score(y_test, rf_preds))

print("LR AUC:", roc_auc_score(y_test, lr.predict_proba(X_test)[:,1]))
print("RF AUC:", roc_auc_score(y_test, rf.predict_proba(X_test)[:,1]))

LR F1: 0.7825664205187501
RF F1: 0.8314014495229264
LR AUC: 0.7843669351168423
RF AUC: 0.8185556013393793

- Stratified split ensures class distribution consistency
- F1 chosen due to imbalance and clinical importance of recall
- AUC evaluates ranking ability of model
- Logistic Regression used as baseline
- Random Forest captures nonlinear relationships
- Final model selected based on combined F1 and AUC performance

# **Hard**

In [100]:
y.value_counts(normalize=True)

target
1    0.594257
0    0.405743
Name: proportion, dtype: float64

In [101]:
from sklearn.metrics import accuracy_score

dummy_preds = np.zeros_like(y_test)
accuracy_score(y_test, dummy_preds)

0.405743625172717

In [102]:
probs = rf.predict_proba(X_test)[:,1]

best_cost = float('inf')
best_thresh = 0.5

for t in np.arange(0.1,0.9,0.05):
    preds = (probs > t).astype(int)

    fn = ((y_test==1) & (preds==0)).sum()
    fp = ((y_test==0) & (preds==1)).sum()

    cost = fn*10 + fp*1

    if cost < best_cost:
        best_cost = cost
        best_thresh = t

best_thresh, best_cost

(0.1, 22302)

In [103]:
import pandas as pd

importance = pd.Series(rf.feature_importances_, index=X.columns)
importance.sort_values(ascending=False).head(10)

resource_usage                       0.232229
Admission_Deposit                    0.158376
Visitors with Patient                0.146376
City_Code_Patient                    0.074159
Available Extra Rooms in Hospital    0.055757
Bed Grade                            0.040103
Hospital_code                        0.032804
Ward_Type_q                          0.025267
Ward_Type_s                          0.021967
Ward_Type_r                          0.015218
dtype: float64

In [104]:
errors = X_test.copy()
errors['actual'] = y_test
errors['pred'] = rf_preds

errors[(errors['actual']==1) & (errors['pred']==0)].head()

,Hospital_code,City_Code_Hospital,Available Extra Rooms in Hospital,Bed Grade,City_Code_Patient,Visitors with Patient,Admission_Deposit,age_group,severity_flag,resource_usage,...,Age_21-30,Age_31-40,Age_41-50,Age_51-60,Age_61-70,Age_71-80,Age_81-90,Age_91-100,actual,pred
46477,21,3,2,4.0,8.0,4,3009.0,1,1,12036.0,...,False,True,False,False,False,False,False,False,1,0
47710,11,2,3,2.0,8.0,2,5589.0,0,1,11178.0,...,False,False,False,False,False,False,False,False,1,0
158167,19,7,3,2.0,8.0,3,3585.0,1,2,10755.0,...,False,True,False,False,False,False,False,False,1,0
315650,14,1,3,3.0,8.0,3,4229.0,2,1,12687.0,...,False,False,False,True,False,False,False,False,1,0
165453,24,1,3,3.0,2.0,7,3255.0,2,1,22785.0,...,False,False,False,False,True,False,False,False,1,0

- Accuracy is misleading due to class imbalance
- Cost-sensitive threshold used to reflect hospital priorities
- False negatives penalized more heavily (missed high-risk patients)
- Feature importance helps interpret model decisions
- Error analysis highlights model failure cases for improvement